### ISSUE TITLE
FDF parser does not handle escaped parentheses

### ISSUE THREAD

**Issue by tadeokondrak** [blamario/canadian-income-tax#2]
To reproduce:

- Download 2023 T1 form
- On page 3, fill in the field `Other income (specify):` with `(testing)`

The FDF generated:

```
<<
/T (Line_13000_Specify[0])
/V (\(testing\))
>>]
>>
```

The error:

```
% complete-canadian-taxes AB --t1 testing.pdf -o completed/ 
complete-canadian-taxes: >>]
>>]
>> 
<<
^
at line 112, column 1
expected string "]"
CallStack (from HasCallStack):
  error, called at app/Main.hs:122:19 in main:Main
```

**Comment by blamario** [comment]
Good catch! That's actually a problem with the https://github.com/blamario/forms-data-format library, I'll fix it there ASAP.
