### ISSUE TITLE
Field name typo?

### ISSUE THREAD

**Issue by tadeokondrak** [blamario/canadian-income-tax#3]
I was reading through some code in this project and spotted a possible typo here (`LIne5` instead of `Line5`):

https://github.com/blamario/canadian-income-tax/blob/d227a891ee8bc6b7e84506166d42fdd53b392fd9/src/Tax/Canada/Province/AB/AB428/FieldNames.hs#L30

**Comment by blamario** [comment]
I agree it's likely a typo, but it's a typo in the PDF rather than the code. The field names are all tested. If you  try to fix the typo in the code, you'll find that it won't be able to load the AB428 form.
